# Generated by Django 5.0.4 on 2024-04-07 17:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roomsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('miqdor', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tolangan_sana', models.DateField(null=True)),
                ('izoh', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BandQilish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('berilgan_sana', models.DateField()),
                ('tark_etgan_sana', models.DateField(null=True)),
                ('jami', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tolandi', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('qoldi', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('joy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roomsApp.joy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
