# Generated by Django 5.0.4 on 2024-04-07 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0001_initial'),
        ('roomsApp', '0001_initial'),
        ('studentsApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guruh',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='joy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roomsApp.joy'),
        ),
        migrations.AddField(
            model_name='student',
            name='tuman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.tuman'),
        ),
    ]
